name: Update and restart script on EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Connect to EC2 and restart script
      uses: appleboy/ssh-action@master

      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        timeout: 40s

        script: |

          (
            echo "### Change directory to the bot folder ###"
            cd ${{ secrets.BOT_DIR }}

            echo "### Current directory ###"
            pwd

            echo "### Kill the bot ###"
            ./kill_bot.sh

            echo "### Pull the latest code ###"
            git pull

            chmod -R 750 ../Chariot

            echo "### Restart the script ###"
            nohup python3 chariot.py > chariot.log 2>&1 &
          )
