name: Update and restart script on EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Connect to EC2 and restart script
      uses: appleboy/ssh-action@master

      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        timeout: 40s

        script: |

          # Change directory to the bot folder
          cd ${{ secrets.BOT_DIR }}

          pwd

          # Kill python3 chariot.py
          echo "Kill 'python3 chariot.py'"
          kill -SIGTERM $(ps aux | grep python3 | grep chariot.py | awk '{print $2}')

          echo "Pull the latest code"
          git pull

          echo "Restart the script"
          nohup python3 chariot.py > chariot.log 2>&1 &