name: Update and restart script on EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Connect to EC2 and restart script
      uses: appleboy/ssh-action@master

      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        timeout: 40s

        script: |

          # Change directory to the bot folder
          cd ${{ secrets.BOT_DIR }}

          # Set process name
          PROCESS_NAME="python3 chariot.py"

          # Check if process is running
          if pgrep -f "$PROCESS_NAME" > /dev/null
          then
              echo "Bot is running."
              # If process is running, kill it
              echo "Kill '$PROCESS_NAME'"
              kill -SIGTERM $(pgrep -f "$PROCESS_NAME")
              sleep 5  # Wait for the process to terminate
          else
              echo "Bot is not running."
              # If process is not running, pass it
          fi

          echo "Pull the latest code"
          git pull

          echo "Restart the script"
          nohup python3 chariot.py > chariot.log 2>&1 &
